version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: .
    image: nginx
    container_name: api-gateway-nginx
    ports:
      - "80:80"
    networks:
      - network-bridge
    depends_on:
      - "products_api"
      - "users_api"
  products_api:
    image: products_api
    container_name: container_products_api
    build:
      dockerfile: ./Dockerfile
      context: ./backends/products/
    networks:
      - network-bridge
  users_api:
    image: users_api
    container_name: container_users_api
    build:
      dockerfile: ./Dockerfile
      context: ./backends/users/
    networks:
      - network-bridge
  users_api_balance:
    image: users_api
    container_name: container_users_api_balance
    build:
      dockerfile: ./Dockerfile
      context: ./backends/users/
    networks:
      - network-bridge
networks:
    network-bridge:
        driver: bridge
